### ISSUE TITLE
add obj_Doesn't work

### ISSUE THREAD

**Issue by 958479612** [UPBGE/UPBGE-logicnodes#59]
https://user-images.githubusercontent.com/82086788/147635161-10b0797a-2014-4bed-8e0c-fcc472479e87.mp4

add obj_Doesn't work.

**Comment by IzaZed** [comment]
The video doesn't work for me
The object you want to add has to be set to invisible (the critical indicator here is the eye icon), but still be on an active collection

**Comment by 958479612** [comment]
> 视频对我不起作用 您要添加的对象必须设置为不可见（此处的关键指示器是眼睛图标），但仍位于活动集合中
Thank you for your reply, follow your prompts, the problem has been resolved,
