### ISSUE TITLE
Mouse Status Node fails to work throughout gameplay

### ISSUE THREAD

**Issue by th3d1n0s4urm4n** [UPBGE/UPBGE-logicnodes#67]
I'm working on a flight sim and am trying to get my aircraft object to roll when turning left or right. I'm using Mouse Status to find when I'm trying to turn left or right, then incrementing a float property, then using that property in an Apply Rotation node:

Mouse Status(X Movement) -> Compare(Greater Than, 0.0) -> Modify Property(Add, Roll_Rate, 0.01)

Get Property(Roll_Rate) ->Vector(X) -> Apply Rotation

In theory, this will find when I'm moving my mouse on the positive X and will then roll the aircraft clockwise.

In testing, this works(kinda). Initially, if I move my mouse to the left, nothing happens. There isn't a decrement for -X movement, so it senses the +X and rolls. However, after that initial test, every time I move my mouse, in any direction, it starts rolling. It's as if Mouse Status becomes Mouse Movement and causes an action any time there's movement.

I could be missusing some of these nodes. I haven't found much documentation to help with mouse nodes, nor are there many tutorials either. I believe this is an unintentional issue. If someone could clarify/help with this issue I'd greatly appreciate it.

**Comment by BluePrintRandom** [comment]
You may need to reset the mouse position to the center of the screen?

As for getting negative values
Try getting mouse position VS center of screen and using that to build your
offset.

**Comment by th3d1n0s4urm4n** [comment]
I think that worked. The aircraft is responding correctly. Thanks!

**Comment by IzaZed** [comment]
I'm closing this as it seems it has been resolved, thank you
